#!/usr/bin/env node
// Generates src/components/worldShapes.ts: the world basemap's SVG paths and country centroids, projected once here
// rather than in every browser on every page load. Re-run after changing the projection or the map data:
//   node apps/web/scripts/world-map.mjs
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { geoCentroid, geoEqualEarth, geoPath } from "d3-geo";
import { feature } from "topojson-client";

const require = createRequire(import.meta.url);
const world = require("world-atlas/countries-110m.json");

const VIEW_W = 960;
const VIEW_H = 400;
const countries = feature(world, world.objects.countries);
const projection = geoEqualEarth().fitExtent([[8, 8], [VIEW_W - 8, VIEW_H - 8]], countries);
const path = geoPath(projection).digits(0);
const round = (n) => Math.round(n);

const shapes = countries.features.map((f) => [String(f.id ?? ""), path(f) ?? ""]).filter(([, d]) => d);
const centroids = Object.fromEntries(
  countries.features
    .filter((f) => f.id)
    .map((f) => [String(f.id), projection(geoCentroid(f))])
    .filter(([, p]) => p)
    .map(([id, [x, y]]) => [id, [round(x), round(y)]]),
);

const out = `// Generated by apps/web/scripts/world-map.mjs from world-atlas (Natural Earth, 1:110m), Equal Earth projection. Don't edit.
export const VIEW_W = ${VIEW_W};
export const VIEW_H = ${VIEW_H};
/** [ISO 3166-1 numeric id, SVG path] per country. */
export const SHAPES: [string, string][] = ${JSON.stringify(shapes)};
/** Projected centroid per ISO 3166-1 numeric id. */
export const CENTROIDS: Record<string, [number, number]> = ${JSON.stringify(centroids)};
`;
writeFileSync(new URL("../src/components/worldShapes.ts", import.meta.url), out);
console.log(`wrote ${shapes.length} shapes, ${(out.length / 1024).toFixed(0)} KB`);
