"""Turn export-sites.sh output into SQL for QWA's D1 database.

Usage: python -I sites_sql.py sites.json > sites.sql
       npx wrangler d1 execute qwa --remote --file sites.sql   (run from apps/worker)

Site ids are kept from Plausible CE, so the imported Parquet files (sites/<id>/...) line up.
Run it against a database with no sites yet.
"""
import json
import sys


def q(v):
    return "'" + str(v).replace("'", "''") + "'"


data = json.load(open(sys.argv[1]))
print("-- generated by tools/import-ce/sites_sql.py from a Plausible CE export")
for s in data["sites"]:
    created = str(s["created_at"]).replace("T", " ")[:19]
    print(
        "INSERT INTO sites (id, domain, timezone, ip_blocklist, created_at) VALUES "
        f"({int(s['ce_id'])}, {q(s['domain'])}, {q(s['timezone'])}, {q(json.dumps(s['ip_blocklist']))}, {q(created)});"
    )
    t = s.get("tracker")
    if t and str(t.get("id", "")).startswith("pa-"):
        print(
            "INSERT INTO compat_scripts (id, site_id, outbound_links, file_downloads, form_submissions) VALUES "
            f"({q(t['id'])}, {int(s['ce_id'])}, {int(bool(t.get('outbound_links')))}, {int(bool(t.get('file_downloads')))}, {int(bool(t.get('form_submissions')))});"
        )
